version: '3.7'
services:

  database-local:
    image: postgres:12.3
    restart: always
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    volumes:
      - nerdAlertData:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  nerdAlertData:
