version: '3.7'
services:

  database-test:
    image: postgres:12.3
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5431:5432"
