version: '3.7'
services:

  database-test:
    image: postgres:12.3
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - nerdAlertTest:/var/lib/postgresql/data
    ports:
      - "5431:5432"

volumes:
  nerdAlertTest:
